### ISSUE TITLE
[FLI-23] Support Memcached

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#1169]
Now that Redis has been rolled out, it should be relatively simple to support another cache tech like Memcached

### TODO

* [ ] Add memcached as a supported caching protocol
* [ ] Support configuring memcached in the config.yml
* [ ] Add example on how to run Flipt with Memcached [Example with Docker Compose](https://gist.github.com/dbist/ebb1f39f580ad9d07c04c3a3377e2bff)

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-23](https://linear.app/flipt/issue/FLI-23/support-memcached)</sub>
